In [1]:
# Import dependencies
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import os

In [2]:
# Set the seed value for the notebook so the results are reproducible
from numpy.random import seed
seed(1)

In [3]:
import tensorflow
tensorflow.keras.__version__

'2.2.4-tf'

In [31]:
# Read csv into a dataframe & drop nan values
df = pd.read_csv(os.path.join("exoplanet_data.csv"))
df = df.dropna()
df.head()

koi_disposition  koi_fpflag_nt  koi_fpflag_ss  koi_fpflag_co  \
0          CONFIRMED              0              0              0   
1     FALSE POSITIVE              0              1              0   
2     FALSE POSITIVE              0              1              0   
3          CONFIRMED              0              0              0   
4          CONFIRMED              0              0              0   
...              ...            ...            ...            ...   
6986  FALSE POSITIVE              0              0              0   
6987  FALSE POSITIVE              0              1              1   
6988       CANDIDATE              0              0              0   
6989  FALSE POSITIVE              0              0              1   
6990  FALSE POSITIVE              0              0              1   

      koi_fpflag_ec  koi_period  koi_period_err1  koi_period_err2  \
0                 0   54.418383     2.479000e-04    -2.479000e-04   
1                 0   19.899140     1.490000e-05    -1.490000e-05   
2                 0    1.736952     2.630000e-07    -2.630000e-07   
3                 0    2.525592     3.760000e-06    -3.760000e-06   
4                 0    4.134435     1.050000e-05    -1.050000e-05   
...             ...         ...              ...              ...   
6986              1    8.589871     1.846000e-04    -1.846000e-04   
6987              0    0.527699     1.160000e-07    -1.160000e-07   
6988              0    1.739849     1.780000e-05    -1.780000e-05   
6989              0    0.681402     2.430000e-06    -2.430000e-06   
6990              1    4.856035     6.360000e-05    -6.360000e-05   

      koi_time0bk  koi_time0bk_err1  ...  koi_steff_err2  koi_slogg  \
0      162.513840          0.003520  ...             -81      4.467   
1      175.850252          0.000581  ...            -176      4.544   
2      170.307565          0.000115  ...            -174      4.564   
3      171.595550          0.001130  ...            -211      4.438   
4      172.979370          0.001900  ...            -232      4.486   
...           ...               ...  ...             ...        ...   
6986   132.016100          0.015700  ...            -152      4.296   
6987   131.705093          0.000170  ...            -166      4.529   
6988   133.001270          0.007690  ...            -220      4.444   
6989   132.181750          0.002850  ...            -236      4.447   
6990   135.993300          0.010800  ...            -225      4.385   

      koi_slogg_err1  koi_slogg_err2  koi_srad  koi_srad_err1  koi_srad_err2  \
0              0.064          -0.096     0.927          0.105         -0.061   
1              0.044          -0.176     0.868          0.233         -0.078   
2              0.053          -0.168     0.791          0.201         -0.067   
3              0.070          -0.210     1.046          0.334         -0.133   
4              0.054          -0.229     0.972          0.315         -0.105   
...              ...             ...       ...            ...            ...   
6986           0.231          -0.189     1.088          0.313         -0.228   
6987           0.035          -0.196     0.903          0.237         -0.079   
6988           0.056          -0.224     1.031          0.341         -0.114   
6989           0.056          -0.224     1.041          0.341         -0.114   
6990           0.054          -0.216     1.193          0.410         -0.137   

             ra        dec  koi_kepmag  
0     291.93423  48.141651      15.347  
1     297.00482  48.134129      15.436  
2     285.53461  48.285210      15.597  
3     288.75488  48.226200      15.509  
4     296.28613  48.224670      15.714  
...         ...        ...         ...  
6986  298.74921  46.973351      14.478  
6987  297.18875  47.093819      14.082  
6988  286.50937  47.163219      14.757  
6989  294.16489  47.176281      15.385  
6990  297.00977  47.121021      14.826  

[6991 rows x 41 columns]

In [28]:
# If I want to see the nan values (in this case there are none)
# Steps to be performed above:

# df.dropna(inplace=True)
# df.head()
# df_nan = df[df.isna().any(axis=1)]
# df_nan
# result is there are no 'nan' values

In [6]:
X = df.drop("koi_disposition", axis=1)
y = df["koi_disposition"]
print(X.shape, y.shape)

(6991, 40) (6991,)


In [7]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
from tensorflow.keras.utils import to_categorical

In [8]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, random_state=1)
print(y_train)
print("y", y)

3563         CANDIDATE
4099         CONFIRMED
5460         CANDIDATE
1091         CONFIRMED
5999         CANDIDATE
             ...      
905          CONFIRMED
5192    FALSE POSITIVE
3980    FALSE POSITIVE
235          CONFIRMED
5157         CONFIRMED
Name: koi_disposition, Length: 5243, dtype: object
y 0            CONFIRMED
1       FALSE POSITIVE
2       FALSE POSITIVE
3            CONFIRMED
4            CONFIRMED
             ...      
6986    FALSE POSITIVE
6987    FALSE POSITIVE
6988         CANDIDATE
6989    FALSE POSITIVE
6990    FALSE POSITIVE
Name: koi_disposition, Length: 6991, dtype: object


In [22]:
X_scaler = MinMaxScaler().fit(X_train)
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)
X_train_scaled

array([[0.        , 0.        , 0.        , ..., 0.83497297, 0.51779124,
        0.5155798 ],
       [0.        , 0.        , 0.        , ..., 0.72693168, 0.38067188,
        0.70650467],
       [0.        , 0.        , 0.        , ..., 0.56436342, 0.80798012,
        0.69823952],
       ...,
       [0.        , 0.        , 1.        , ..., 0.88419373, 0.2724652 ,
        0.74055707],
       [0.        , 0.        , 0.        , ..., 0.38035748, 0.58629009,
        0.733697  ],
       [0.        , 0.        , 0.        , ..., 0.25722845, 0.72706515,
        0.59980164]])

In [10]:
# Step 1: Label-encode data set
label_encoder = LabelEncoder()
label_encoder.fit(y_train)
encoded_y_train = label_encoder.transform(y_train)
encoded_y_test = label_encoder.transform(y_test)
print(encoded_y_train)

[0 1 0 ... 2 1 1]


In [11]:
y_train.unique()

array(['CANDIDATE', 'CONFIRMED', 'FALSE POSITIVE'], dtype=object)

In [12]:
# Step 2: Convert encoded labels to one-hot-encoding
y_train_categorical = to_categorical(encoded_y_train)
y_test_categorical = to_categorical(encoded_y_test)
print(y_train_categorical)

[[1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 ...
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]]


In [13]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [14]:
# Create model and add layers
model = Sequential()
model.add(Dense(units=100, activation='relu', input_dim=40))
model.add(Dense(units=100, activation='relu'))
model.add(Dense(units=3, activation='softmax'))

In [15]:

print(y_test_categorical.shape)

(1748, 3)


In [16]:
# Compile and fit the model
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

In [17]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 100)               4100      
_________________________________________________________________
dense_1 (Dense)              (None, 100)               10100     
_________________________________________________________________
dense_2 (Dense)              (None, 3)                 303       
Total params: 14,503
Trainable params: 14,503
Non-trainable params: 0
_________________________________________________________________


In [18]:
model.fit(
    X_train_scaled,
    y_train_categorical,
    epochs=60,
    shuffle=True,
    verbose=2
)

Train on 5243 samples
Epoch 1/60
5243/5243 - 1s - loss: 0.5796 - accuracy: 0.7145
Epoch 2/60
5243/5243 - 0s - loss: 0.3746 - accuracy: 0.8140
Epoch 3/60
5243/5243 - 0s - loss: 0.3686 - accuracy: 0.8119
Epoch 4/60
5243/5243 - 0s - loss: 0.3551 - accuracy: 0.8247
Epoch 5/60
5243/5243 - 0s - loss: 0.3471 - accuracy: 0.8299
Epoch 6/60
5243/5243 - 0s - loss: 0.3346 - accuracy: 0.8415
Epoch 7/60
5243/5243 - 0s - loss: 0.3315 - accuracy: 0.8421
Epoch 8/60
5243/5243 - 0s - loss: 0.3240 - accuracy: 0.8465
Epoch 9/60
5243/5243 - 0s - loss: 0.3207 - accuracy: 0.8503
Epoch 10/60
5243/5243 - 0s - loss: 0.3177 - accuracy: 0.8526
Epoch 11/60
5243/5243 - 0s - loss: 0.3182 - accuracy: 0.8539
Epoch 12/60
5243/5243 - 0s - loss: 0.3156 - accuracy: 0.8566
Epoch 13/60
5243/5243 - 0s - loss: 0.3141 - accuracy: 0.8566
Epoch 14/60
5243/5243 - 0s - loss: 0.3068 - accuracy: 0.8596
Epoch 15/60
5243/5243 - 0s - loss: 0.3061 - accuracy: 0.8631
Epoch 16/60
5243/5243 - 0s - loss: 0.2976 - accuracy: 0.8703
Epoch 17/60

In [19]:
model.summary

<bound method Network.summary of <tensorflow.python.keras.engine.sequential.Sequential object at 0x000001B0CFAD3A90>>

In [20]:
model_loss, model_accuracy = model.evaluate(X_test_scaled, y_test_categorical, verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

1748/1748 - 0s - loss: 0.2341 - accuracy: 0.9022
Loss: 0.23413013436701532, Accuracy: 0.9021739363670349
